//------------------------------------------------------------------------------
// <auto-generated>

using System.ComponentModel.DataAnnotations;

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MdCatagory
    {
        [Key]
        public int id { get; set; }

        [Display(Name = "نام")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Name { get; set; }

        public int? CatagoryId { get; set; }
    }
}
