//------------------------------------------------------------------------------
// <auto-generated>

using System.ComponentModel.DataAnnotations;

namespace DataLayer.Models
{
    public partial class MdImage
    {
        [Key]
        public int id { get; set; }

        [Display(Name = "عکس")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Image { get; set; }
        
    }
}
