//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductCommentRel
    {
        public int id { get; set; }
        public int ProductId { get; set; }
        public int CommentId { get; set; }
    
        public virtual TblComment TblComment { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
