//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models.Regular
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDealPropertyRel
    {
        public int id { get; set; }
        public int DealId { get; set; }
        public int PropertyId { get; set; }
    
        public virtual TblDeal TblDeal { get; set; }
        public virtual TblProperty TblProperty { get; set; }
    }
}
