//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer.Models.Regular
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblLive()
        {
            this.TblClientProductRel = new HashSet<TblClientProductRel>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public string Chanel { get; set; }
        [Required(ErrorMessage = "این فیلد باید پر شود")]
        public string MainImage { get; set; }
        public string DescriptionShort { get; set; }
        public string DescriptionLong { get; set; }
        public System.DateTime TimeStart { get; set; }
        public Nullable<long> Price { get; set; }
        public bool IsHome { get; set; }
        public int ToutorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblClientProductRel> TblClientProductRel { get; set; }
        public virtual TblTutor TblTutor { get; set; }
    }
}
