//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models.Regular
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLog
    {
        public int id { get; set; }
        public string LogText { get; set; }
        public long MoneyTransfered { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
