//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models.Regular
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProduct()
        {
            this.TblClientProductRel = new HashSet<TblClientProductRel>();
            this.TblProductCommentRel = new HashSet<TblProductCommentRel>();
            this.TblProductImageRel = new HashSet<TblProductImageRel>();
            this.TblProductKeywordRel = new HashSet<TblProductKeywordRel>();
            this.TblProductPropertyRel = new HashSet<TblProductPropertyRel>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string DateSubmited { get; set; }
        public int Raiting { get; set; }
        public long Price { get; set; }
        public string DescriptionHtml { get; set; }
        public Nullable<int> CatagoryId { get; set; }
        public int Count { get; set; }
        public bool IsSuggested { get; set; }
        public int Discount { get; set; }
        public int Status { get; set; }
    
        public virtual TblCatagory TblCatagory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblClientProductRel> TblClientProductRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductCommentRel> TblProductCommentRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductImageRel> TblProductImageRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductKeywordRel> TblProductKeywordRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductPropertyRel> TblProductPropertyRel { get; set; }
    }
}
