//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models.Regular
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVideo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblVideo()
        {
            this.TblTuotorVideoRel = new HashSet<TblTuotorVideoRel>();
        }
    
        public int id { get; set; }
        public string VideoUrl { get; set; }
        public string VidioDemoUrl { get; set; }
        public string MainImage { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DescriptionDemo { get; set; }
        public string DateSubmited { get; set; }
        public bool IsOnline { get; set; }
        public int ViewCount { get; set; }
        public bool IsHome { get; set; }
        public int Raiting { get; set; }
        public string ShareLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTuotorVideoRel> TblTuotorVideoRel { get; set; }
    }
}
